### ISSUE TITLE
Strange behavior when show toolbar on focus...

### ISSUE THREAD

**Issue by AlexVKO** [textAngular/textAngular#1025]
Hello everyone,

I have a lot of text-area in the same page. And with the purpose of getting cleaner,  I opted to use this css classes to show/hide toolbar on focus/blur.

``` css
.ta-root .ta-toolbar{ display: none; }
.ta-root.focussed .ta-toolbar{ display: block; }
```

But, for instance, when I finish the content, I have to click twice on submit button (or whatever)... one for blur the text area, and another one for submit the form...

is there a workaround ?

Thank you very much for your excellent work.
